// <auto-generated />
using animesplanetserver.DataService.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace animesplanetserver.Migrations
{
    [DbContext(typeof(AnimesPlanetDataContext))]
    [Migration("20180510143737_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("animesplanetserver.Model.Anime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AiringDate");

                    b.Property<string>("CoverPicture");

                    b.Property<string>("Description");

                    b.Property<int>("NumberOfEpisodes");

                    b.Property<string>("Stori");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Animes");
                });

            modelBuilder.Entity("animesplanetserver.Model.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AnimeId");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<string>("Pictures");

                    b.HasKey("Id");

                    b.HasIndex("AnimeId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("animesplanetserver.Model.EpicMoment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AnimeId");

                    b.Property<int>("Anime_Id");

                    b.Property<int>("Path");

                    b.HasKey("Id");

                    b.HasIndex("AnimeId");

                    b.ToTable("EpicMoments");
                });

            modelBuilder.Entity("animesplanetserver.Model.Music", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AnimeId");

                    b.Property<int>("Anime_Id");

                    b.Property<string>("Path");

                    b.HasKey("Id");

                    b.HasIndex("AnimeId");

                    b.ToTable("Musics");
                });

            modelBuilder.Entity("animesplanetserver.Model.Picture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AnimeId");

                    b.Property<int>("Anime_Id");

                    b.Property<string>("Path");

                    b.HasKey("Id");

                    b.HasIndex("AnimeId");

                    b.ToTable("Pictures");
                });

            modelBuilder.Entity("animesplanetserver.Model.Character", b =>
                {
                    b.HasOne("animesplanetserver.Model.Anime")
                        .WithMany("Characters")
                        .HasForeignKey("AnimeId");
                });

            modelBuilder.Entity("animesplanetserver.Model.EpicMoment", b =>
                {
                    b.HasOne("animesplanetserver.Model.Anime")
                        .WithMany("EpicMoments")
                        .HasForeignKey("AnimeId");
                });

            modelBuilder.Entity("animesplanetserver.Model.Music", b =>
                {
                    b.HasOne("animesplanetserver.Model.Anime")
                        .WithMany("Musics")
                        .HasForeignKey("AnimeId");
                });

            modelBuilder.Entity("animesplanetserver.Model.Picture", b =>
                {
                    b.HasOne("animesplanetserver.Model.Anime")
                        .WithMany("Pictures")
                        .HasForeignKey("AnimeId");
                });
#pragma warning restore 612, 618
        }
    }
}
